name: Commit Run

on:
  push: # Uruchamiaj workflow przy każdym pushu (commit)

env:
    CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}
    CF_ACCOUNT_API: ${{ secrets.CF_ACCOUNT_API }}
    DB_ID: ${{ secrets.DB_ID }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pobierz biblioteki
        run: pip install -r requirements.txt
        
      - name: Run tests (przykład)
        run: python3 scan_directories.py
